# Generated by Django 3.2.3 on 2021-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='game_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticker_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
