# Generated by Django 3.2.3 on 2021-05-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210519_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticker_id',
            new_name='ticket_id',
        ),
    ]
