# Generated by Django 3.2.3 on 2021-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_ticket_bought_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='bought_by',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
