# Generated by Django 3.2.3 on 2021-05-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_type', models.CharField(choices=[('FR', 'Top Row'), ('MR', 'Middle Row'), ('BR', 'Bottom Row'), ('Q5', 'Quick Five'), ('CO', 'Corners'), ('SR', 'Star'), ('HF', 'House Full'), ('SHF', 'Second House Full')], default='', max_length=3)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.winners'),
        ),
    ]
