# Generated by Django 3.2.3 on 2021-05-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210522_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Winners',
            new_name='Winner',
        ),
    ]
