# Generated by Django 3.2.3 on 2021-05-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_game_winners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winners',
        ),
        migrations.AddField(
            model_name='winner',
            name='game_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.game'),
        ),
    ]
