# Generated by Django 3.2.3 on 2021-05-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210522_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='booking_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='drawn_numbers_list',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='last_played_num',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='last_played_winner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
