# Generated by Django 3.2.3 on 2021-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210522_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='booking_open',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_status',
        ),
        migrations.AddField(
            model_name='game',
            name='game_is_live',
            field=models.BooleanField(default=False),
        ),
    ]
