# Generated by Django 3.2.3 on 2021-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210522_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='win_type',
            field=models.CharField(choices=[('TR', 'Top Row'), ('MR', 'Middle Row'), ('BR', 'Bottom Row'), ('Q5', 'Quick Five'), ('CO', 'Corners'), ('SR', 'Star'), ('HF', 'House Full'), ('SHF', 'Second House Full')], default='', max_length=3),
        ),
    ]
