# Generated by Django 3.2.3 on 2021-05-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210522_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='game_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='profiles.game'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='profiles.ticket'),
        ),
    ]
