# Generated by Django 3.2.3 on 2021-05-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210522_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='profiles.game'),
        ),
    ]
