# Generated by Django 3.2.3 on 2021-05-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_rename_winner_id_winner_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
