# Generated by Django 3.2.3 on 2021-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_rename_ticket_id_winner_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
