# Generated by Django 3.2.3 on 2021-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_alter_game_last_played_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='drawn_numbers_list',
            field=models.CharField(default='', max_length=500),
        ),
    ]
